/**
 *  Types are used to allow the Actions and Reducers to communicate between each other.
 *  They are simply strings that tell the Reducer what to do
 * */

// Auth Types
export const LOGIN_USER = "LOGIN_USER";
export const LOADING = "LOADING";
export const GET_ERROR = "ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

// HubSpot Types
export const HUBSPOT_TYPES = {
  GET_ENGAGEMENTS: "GET_ENGAGEMENTS",
  GET_CONTACTS: "GET_CONTACTS",
  ENGAGEMENTS_LOADING: "ENGAGEMENTS_LOADING",
  CONTACTS_LOADING: "CONTACTS_LOADING",
  HSPOT_ERROR: "HSPOT_ERROR",
};

// Clients Types
export const CLIENTS_TYPES = {
  GET_CLIENTS: "GET_CLIENTS",
  UPDATE_CLIENTS: "UPDATE_CLIENTS",
  DELETE_CLIENTS: "DELETE_CLIENTS",
  CLIENTS_LOADING: "CLIENTS_LOADING",
  CLIENTS_ERROR: "CLIENTS_ERROR",
  GET_CLIENTS_BY_ID: "GET_CLIENTS_BY_ID",
  CLIENTS_BY_ID_LOADING: "CLIENTS_BY_ID_LOADING",
  CLIENTS_BY_ID_ERROR: "CLIENTS_BY_ID_ERROR",
  UPDATE_CLIENT_ERROR: "UPDATE_CLIENT_ERROR",
  GET_CLIENTS_TRANSACTIONS: "GET_CLIENTS_TRANSACTIONS",
};

// Notes Types
export const NOTES_TYPES = {
  GET_NOTES_BY_CLIENT: "GET_NOTES_BY_CLIENT",
  GET_NOTE_BY_ID: "GET_NOTE_BY_ID",
  CREATE_NOTES: "CREATE_NOTES",
  UPDATE_NOTES: "UPDATE_NOTES",
  DELETE_NOTES: "DELETE_NOTES",
  NOTES_LOADING: "NOTES_LOADING",
  NOTES_ERROR: "NOTES_ERROR",
  NOTES_UPDATING: "NOTES_UPDATING",
  GET_RECENT_NOTES: "GET_RECENT_NOTES"
};

export const USERS_TYPES = {
  GET_USER_BY_ID: "GET_USER_BY_ID",
  USERS_LOADING: "USERS_LOADING",
  USERS_ERROR: "USERS_ERROR",
  GET_ALL_USERS: "GET_ALL_USERS",
};

export const JOBS_TYPES = {
  GET_JOBS: "GET_JOBS",
  GET_JOB_BY_ID: "GET_JOB_BY_ID",
  GET_JOBS_EXPECT: "GET_JOBS_EXPECT",
  JOBS_LOADING: "JOBS_LOADING",
  JOBS_ERROR: "JOBS_ERROR",
  JOB_LOADING: "JOB_LOADING",
  JOB_ERROR: "JOB_ERROR",
  GET_JOB_COUNTS: "GET_JOBS_COUNT",
};
